# Generated by Django 5.1.6 on 2025-02-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0008_fechaaprobado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='day',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='start_time',
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='disp',
            field=models.JSONField(default=list),
        ),
    ]
