# Generated by Django 5.1.6 on 2025-03-05 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0009_remove_disponibilidad_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnosInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumnos', models.JSONField(default=list)),
                ('instructor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos_instructor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
